### ISSUE TITLE
Add pkgdown site?

### ISSUE THREAD

**Issue by seananderson** [vast-lib/tinyVAST#13]
Do you want me to set up a pkgdown site? E.g. https://pbs-assess.github.io/sdmTMB/  It's fairly straightforward and relies on the existing files + a bit of configuration. Important if you want to display 'Articles' and a better place to have rendered vignettes than in the vignettes folder itself on github.

**Comment by James-Thorson-NOAA** [comment]
Do you know where I need to store figures for pre-built vignettes in the vignettes/web_only directory?

If you look at branch "add_header" you'll see that I tried putting them everywhere I could think of:

- man/figures
- vignettes
- vignettes/web_only
- vignettes/web_only/figures

and they still don't render on the local build using `pkgdown::build_site( examples=TRUE )` with warning messages below.  I also didn't immediately find anything helpful by googling.  Any ideas offhand?

```R

-
Warning messages:


\
1: Missing images in 'vignettes/web_only/age_composition_expansion.Rmd': 'figure/agecomp-1.png'

ℹ pkgdown can only use images in 'man/figures' and 'vignettes' 

2: Missing images in 'vignettes/web_only/empirical_orthogonal_functions.Rmd': 'figure/EOF-1.png'

ℹ pkgdown can only use images in 'man/figures' and 'vignettes' 

3: The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata. The former is "VAST", and the latter is "Vector autoregressive spatio-temporal models". If that is intentional, you may set options(rmarkdown.html_vignette.check_title = FALSE) to suppress this check. 

4: Missing images in 'vignettes/web_only/VAST.Rmd': 'figure/VAST-true-dens-1.png', 'figure/VAST-est-dens-1.png', 'figure/VAST-scatterplot-1.png', 'figure/VAST-abundance-1.png', 'figure/VAST-VAR-index-1.png'

ℹ pkgdown can only use images in 'man/figures' and 'vignettes' 


```

**Comment by seananderson** [comment]
Does this help?
https://pkgdown.r-lib.org/reference/build_articles.html#external-files

**Comment by James-Thorson-NOAA** [comment]
I worked it out from looking at the compiled html files ... the warnings had said to use a dir `figures` but it was instead looking for a dir `figure`.  Now fixed, and you can see the compiled site on `add_header` branch.  I'll work on merges today.
