### ISSUE TITLE
Add codecov

### ISSUE THREAD

**Issue by James-Thorson-NOAA** [vast-lib/tinyVAST#20]
@seananderson do you have any scratch script showing how you interacted with codecov to get it set up for sdmTMB?

I wanna start getting that set up for tinyVAST and I'd welcome any quick pointers before I dive in.

**Comment by James-Thorson-NOAA** [comment]
I've a bunch of integrated-tests and run them through the codecov Action. For some reason, the stream-network model has a cryptic error [here](https://github.com/vast-lib/tinyVAST/actions/runs/7591605053/job/20679889942) when I uncomment the lines below, even though it passes R-CMD-checks.  Do you have any insight?

#  out = tinyVAST( data = Data,
#             formula = Count ~ 1,
#             spatial_graph = graph,
#             space_column = c("X","Y"),
#             variable_column = "var",
#             time_column = "time",
#             distribution_column = "dist",
#             sem = "" )

**Comment by seananderson** [comment]
I can’t see the error message from my phone right now… but I do remember
the stream network vignette was crashing in R CMD check, which is one
reason I stopped vignette checks in the GitHub actions R CMD check.
