### ISSUE TITLE
Update delta-model family functions

### ISSUE THREAD

**Issue by James-Thorson-NOAA** [vast-lib/tinyVAST#34]
Collapse delta_gamma and delta_poisson_link_gamma etc, following lead of sdmTMB

**Comment by seananderson** [comment]
I did this over in sdmTMB in this branch: https://github.com/pbs-assess/sdmTMB/tree/newdeltas

See the last commit.

I'm just waiting for all the checks to run before merging into main. I also removed the hardwiring of the delta family links. Probably simplest just to import/re-export these.

**Comment by seananderson** [comment]
I now realize the 'clean names' still have hardwired links, but I'll make an issue and deal with that later. It's slightly tricky because people can use `"log"` or `log` etc.

**Comment by seananderson** [comment]
This has been merged into the main sdmTMB branch including a fix for the 'clean name' links. I suppose we'll have to copy the code into tinyVAST for now because the CRAN version of sdmTMB doesn't have the new function arguments.

**Comment by James-Thorson-NOAA** [comment]
I see that the latest sdmTMB release on github and CRAN 0.4.2 is about a month old.  do you anticipate doing a CRAN release with the updated delta-model stuff soon (in which case I'll switch to using exported functions from sdmTMB for tinyVAST family functions), or any insight on timeline?

**Comment by seananderson** [comment]
I should get a new CRAN release up shortly. For one, those new delta families affect examples in the preprint and submitted revision. Maybe over the next couple weeks? I'll post a release checklist as an issue.

**Comment by James-Thorson-NOAA** [comment]
now done, thanks Sean :)
