### ISSUE TITLE
Spatially Varying Coefficient (SVC) Support

### ISSUE THREAD

**Issue by samc1088** [vast-lib/tinyVAST#45]
Support for spatially varying coefficients (like the spatially_varying function in sdmTMB) to allow covariates to interact with the spatial field would be great!

**Comment by James-Thorson-NOAA** [comment]
Thanks for suggesting it!  Also requested by @agruss2, @cheryl-barnes, and @reumj.  

I just added it to the tinyVAST@dev branch, with a simple test [here](https://github.com/vast-lib/tinyVAST/blob/add_SVC/tests/testthat/test-SVC.R).  Are any of y'all willing to test it out?
